# Generated by Django 6.0.4 on 2026-04-17 23:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='capa_url',
            new_name='cover_url',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='descricao',
        ),
        migrations.AddField(
            model_name='livro',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
