# Generated by Django 6.0.4 on 2026-04-21 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_autor_livro_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='google_volume_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='livro',
            constraint=models.UniqueConstraint(fields=('user', 'google_volume_id'), name='unique_user_book'),
        ),
    ]
