# Generated by Django 6.0.4 on 2026-04-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_livro_google_volume_id_livro_unique_user_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='isbn',
        ),
    ]
