# Generated by Django 6.0.4 on 2026-04-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_livro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='user_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
